### PR TITLE
Update StatsBase version bound

### PR DESCRIPTION
**Pull request by oschulz**

### CODE REVIEW

**Comment by oschulz** [comment]
Tests pass locally.

**Comment by oschulz** [comment]
Thanks @mauriciogtec - could you trigger Registrator (version number is already increased in Project.toml)?

**Comment by mauriciogtec** [comment]
It should be done now. (I set a new release)

**Comment by oschulz** [comment]
> It should be done now. (I set a new release)

But setting a release manually doesn't get it into https://github.com/JuliaRegistries/General/blob/master/A/AdaptiveRejectionSampling/Versions.toml :-)

I think you need to add a `@JuliaRegistrator register` comment to

https://github.com/mauriciogtec/AdaptiveRejectionSampling.jl/commit/d89463752df6bbbda6544d6f1b53ef955f2e0c04

(just like my comment there, only I don't have the necessary rights).

**Pull request merged**
